name: BatMembranes
version: 1.2
main: me.minecraft.plugin.batMembranes.BatMembranes
api-version: 1.21
authors: [ JustErikSK ]
description: Bats drop membranes instead of phantoms - those are disabled but can still be enabled with the config file!
folia-supported: true